version: '3'

services:
  backend:
    build: backend/.
    ports:
      - "8080:8080"
    networks:
      mynetwork:
        ipv4_address: 172.23.0.3
  frontend:
    build: "frontend/."
    environment:
      - PUBLIC_BACKEND_URL=http://172.23.0.3:8080/server
      - PUBLIC_SOCKET_URL=ws://172.23.0.3:8080/server
    ports:
      - "5173:5173"
    networks:
      mynetwork:
        ipv4_address: 172.23.0.4

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24